language: cpp
sudo: required
dist: precise
env:
 - MCPATH=${TRAVIS_BUILD_DIR}/config

before_install:
 - sudo apt-get install tcl-dev
 - sudo apt-get install libboost-dev
 - sudo apt-get install libboost-iostreams-dev
 - sudo apt-get install libsuperlu3-dev
 - sudo apt-get install liblapack-dev

install: true
script: make travis
after_success: cd test && ./runAll.sh
