all: as_si_100_8_  b_si_0_  b_si_100_7_  damage_si_

as_si_100_8_:
	cd As_Si_100_8;\
	make

b_si_0_:
	cd B_Si_0;\
	make

b_si_100_7_:
	cd B_Si_100_7;\
	make

damage_si_:
	cd Damage_Si;\
	make

plot:
	cd As_Si_100_8;\
	make plot
	cd B_Si_0;\
	make plot
	cd B_Si_100_7;\
	make plot
	cd Damage_Si;\
	make plot

clean:
	cd As_Si_100_8;\
	make clean
	cd B_Si_0;\
	make clean
	cd B_Si_100_7;\
	make clean
	cd Damage_Si;\
	make clean
    