all: se_gaas_ si_gaas_

se_gaas_:
	cd Se_GaAs;\
	make

si_gaas_:
	cd Si_GaAs;\
	make

plot:
	cd Se_GaAs;\
	make plot
	cd Si_GaAs;\
	make plot

clean:
	cd Se_GaAs;\
	make clean
	cd Si_GaAs;\
	make clean
